### DISCUSSION TITLE
JSON Parse error when signing in with Authelia

### DISCUSSION THREAD

**Discussion by DMJ743** [9p4/jellyfin-plugin-sso#241] [Q&A]
When I attempt to authenticate using Authelia, I get the following error when getting redirected from Authelia back to Jellyfin:

```
Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    main https://tv.example.com/sso/OID/redirect/authelia?code=authelia_ac_DopaUYlUd4UMD1ab8JrITe0fGdXYw9PmTC1_popau78.8Ixi0NINInWjKy2fYEyZ09dmWRG2ZwT1P7RmR1CQVd8&iss=https://auth.example.com&scope=openid+profile+groups&state=RVZ8L2lBg2Bj4k_RnToRrQ:467
    async* https://tv.example.com/sso/OID/redirect/authelia?code=authelia_ac_DopaUYlUd4UMD1ab8JrITe0fGdXYw9PmTC1_popau78.8Ixi0NINInWjKy2fYEyZ09dmWRG2ZwT1P7RmR1CQVd8&iss=https://auth.example.com&scope=openid+profile+groups&state=RVZ8L2lBg2Bj4k_RnToRrQ:480
    EventListener.handleEvent* https://tv.example.com/sso/OID/redirect/authelia?code=authelia_ac_DopaUYlUd4UMD1ab8JrITe0fGdXYw9PmTC1_popau78.8Ixi0NINInWjKy2fYEyZ09dmWRG2ZwT1P7RmR1CQVd8&iss=https://auth.example.com&scope=openid+profile+groups&state=RVZ8L2lBg2Bj4k_RnToRrQ:479
authelia:467:29
```

Specifically, it's this attempt to parse JSON in main() that's failing:
```
  let response = await new Promise(resolve => {
       var xhr = new XMLHttpRequest();
       xhr.open('POST', url, true);
       xhr.setRequestHeader('Content-Type', 'application/json');
       xhr.setRequestHeader('Accept', 'application/json');
       xhr.onload = function(e) {
         resolve(xhr.response);
       };
       xhr.onerror = function () {
         resolve(undefined);
       };
       xhr.send(JSON.stringify(request));
    })
    var responseJson = JSON.parse(response); #Fails here
```

Here's the relevant Authelia config portion:
```
- client_id: '{random string}'
  client_name: 'jellyfin'
  client_secret: '$pbkdf2-sha512{PW Hash}
  authorization_policy: 'one_factor'
  redirect_uris:
      - 'https://tv.example.com/sso/OID/redirect/authelia'
  scopes:
      - 'openid'
      - 'profile'
      - 'groups'
  token_endpoint_auth_method: 'client_secret_post'
```

I don't know a ton about web debugging, so I can't quite figure out how to inspect what the contents of ```response``` is in order to troubleshoot. Any help would be appreciated!
