### ISSUE TITLE
Document How to set login disclaimer + branding css to add SSO links to frontpage

### ISSUE THREAD

**Issue by strazto** [9p4/jellyfin-plugin-sso#16]
_Originally posted by @matthewstrasiotto in https://github.com/9p4/jellyfin-plugin-sso/issues/2#issuecomment-1103446246_

- [ ] Optionally, (and later) write frontend that autmatically injects this into the user's disclaimer settings 
   - [ ] can probably use css to distinguish provider graphics
   
An example - Here, I:
- add links that I style to match the native buttons (Forgot password, Quick Connect, etc),
  - Password Reset via authelia,
  - Server homepage 
- use css to hide the Forgot Password button, since my Audentity Provider is LDAP, and authelia provides password reset functionality (There's no setting for this)

```html
<a href="https://authelia.example.com/reset-password/step1" class="raised cancel block emby-button">Forgot Password</a>
<a href="https://example.com" class="raised cancel block emby-button">
   <span class="material-icons home" aria-hidden="true"></span>
   <span>Server Homepage</span>
</a>
```

```css
/* Hide this in lieu of authelia link */
.emby-button.block.btnForgotPassword {
   display: none;
}

/* Make links look like buttons */
a.raised.emby-button { 
   padding: 0.9em 1em;
   color: inherit !important;
}


/* Let disclaimer take full width */
.disclaimerContainer {
   display: block;
}
```

This renders out like so:

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/39424834/164383509-20461ad1-63c2-40a6-976a-959768c75f19.png">

"Manual Login" and "Quick Connect" are both builtin by jellyfin, "Forgot Password" is actually my own link to authelia.

**Comment by matthewstrasiotto** [comment]
to begin with, supporting "Sign on with authelia" would look like:

Login Disclaimer:
```html
<a href="https://myjellyfin.example.com/sso/OID/p/authelia" class="raised cancel block emby-button authelia-sso">Sign in with Authelia</a>
```

Custom CSS code:

```css
/* Make links look like buttons */
a.raised.emby-button { 
   padding: 0.9em 1em;
   color: inherit !important;
}


/* Let disclaimer take full width */
.disclaimerContainer {
   display: block;
}

/* Optionally, apply some styling to the `.authelia-sso` class, probably let users configure this */
.authelia-sso {
   /* idk set a background image or something lol */
}
```

**Comment by 9p4** [comment]
I'm planning on restructuring the login flow just a little to accommodate this (as well as solve the issue of when the web frontend is on a different domain than the JF server). The plan is to have everything work as a programmatic API, so instead of returning a webpage, it'll return JSON or something similar and other endpoints can use that API to set cookies or whatever. Then, with this, we can set it so that the button loads some JS that interacts with the API and sets the relevant information instead. The flow would look something like this:

1. User loads JF, presses on button
2. Button executes some JS to send a "start auth" to SSO API
3. SSO API returns a URL to load to auth with
4. Button JS opens URL in new tab
5. Once the URL has finished authentication, it will redirect back to the API
6. Button JS has been polling API "is auth done yet" and finally gets response once callback has occurred
7. Button JS gets data and uses it to log the user in 

I think it can be simplified at some points. What do you think?

**Comment by fservida** [comment]
Just putting also my input as I’ve been working hard to implement sso in different services, I’m not sure opening a secondary tab is the best UX in term of sso.

Also, and maybe more important, make sure automatic sso can still be available, either with something similar to the current endpoints, or (and probably better) a configuration point telling the JS script to automatically start the login flow.
I’ve contributed something similar (although using headers and not saml/oidc) to ombi.

**Comment by 9p4** [comment]
So the flow would be something like this:

1. User loads JF, presses on button
1. Button executes some JS to send a "start auth" to SSO API
1. Button JS sets a cookie with the ID of the SSO "start"
1. SSO API returns a URL to load to auth with
1. Button JS opens URL
1. Once the URL has finished authentication, it will redirect back to the API, which will redirect to the frontend
1. Button JS checks if cookie for "start" exists, and if so, it will use the token in the cookie to get information. If not, nothing happens (step 1)
1. Button JS gets data and uses it to log the user in

**Comment by matthewstrasiotto** [comment]
Ah sorry - I think i mean to reply with my own take on how to approach SSO flow - 

Basically - it seems that you're implying that we add some custom javascript to the login page that handles some aspects of the flow.

Although this sounds nice,  I do not believe there exists an API that would allow a plugin to inject javascript / `<script>` elements to arbitrary pages, which would make this challenging.

The webui (correctly) runs `DOMPurify` on any user created html, before it's rendered (For example, the login disclaimer). 

For now, I'm unsure how to address this, but the new-tab approach should be "good enough" for a while.

**Comment by matthewstrasiotto** [comment]
For my own reference, here is the setting pattern used to configure loginDisclaimer & branding css:

https://github.com/jellyfin/jellyfin-web/blob/81e240d50dfeda096d7f8b5fc44311ec6d8625fc/src/controllers/dashboard/general.js#L38-L45 

Get pattern for login disclaimer:

https://github.com/jellyfin/jellyfin-web/blob/81e240d50dfeda096d7f8b5fc44311ec6d8625fc/src/controllers/session/login/index.js#L286-L290

Get pattern for custom css + disclaimer:

https://github.com/jellyfin/jellyfin-web/blob/81e240d50dfeda096d7f8b5fc44311ec6d8625fc/src/controllers/dashboard/general.js#L55

https://github.com/jellyfin/jellyfin-web/blob/81e240d50dfeda096d7f8b5fc44311ec6d8625fc/src/controllers/dashboard/general.js#L106-L109

**Comment by matthewstrasiotto** [comment]
Matrix conversation exerpt

> Matthew Strasiotto
> As I understand it, Jellyfin presently doesn't allow plugins to inject JavaScript to any page except their own plugin pages.
> I'm curious if the Devs would consider allowing plugins to do that?
> lakerssuperman2 joined the room.
> Niels
> What would your use case for such a feature be?
> Matthew Strasiotto
> Niels https://github.com/9p4/jellyfin-plugin-sso  , for example, js based flows for authenticating with OIDC
> 
> GitHub - 9p4/jellyfin-plugin-sso: This plugin allows users to sign in through an SSO provider (such as Google, Microsoft, or your own provider). This enables one-click signin. - GitHub
> This plugin allows users to sign in through an SSO provider (such as Google, Microsoft, or your own provider). This enables one-click signin. - GitHub - 9p4/jellyfin-plugin-sso: This plugin allows ...
> Niels
> I don't think supporting such a thing with js plugins in the frontend is really feasible
> Matthew Strasiotto
> what do you mean by that?
> Niels
> You want to inject a complete user interface with javascript, that's not going to work when the UI is managed by React. It would also 100% break for every release
> Matthew Strasiotto
> I'm aware that it would only apply to the web-ui & web-wrapper apps, but that doesn't bother me as that means that the same client-side plugin code can apply to the same view across like 4 platforms
> hm, I don't think I'd want to inject a complete UI with JS, it'd be more along the lines of "check headers, perform auth", maybe inject an ivew for a redirect (if that's feasible) 
> i don't actually know how feasible that specific scenario is for OIDC flows in general, I'd need to double check
> so specifics of that scenario i put forward aside, imagine someone just wants to add a button that performs some action, for example, generates a share link for a file, or triggers an opensubtitle download for the currently viewed item
> am i right in thinking that there's currently no mechanic within the plugin api to perform these actions?
> Niels
> That's not possible no, it would be very difficult to support
> Matthew Strasiotto
> ok, fair enough

**Comment by 9p4** [comment]
The ideal option would be to integrate this plugin as part of the official JF spec for better frontend support, but that would be complex to maintain, and I don't know if I can manage that.

In the meantime, web-based auth in conjunction with Quick-Connect should handle 99% of the use-case.

**Comment by matthewstrasiotto** [comment]
> The ideal option would be to integrate this plugin as part of the official JF spec for better frontend support, but that would be complex to maintain, and I don't know if I can manage that.

Yep, the maintainers seem pretty resistant since it would imply that every since client would have to bring its own implementation of OIDC auth

> In the meantime, web-based auth in conjunction with Quick-Connect should handle 99% of the use-case.

yeah, when 10.8 gets full-released, pretty much all major clients will have implemented quick-connect

**Comment by FirbyKirby** [comment]
I've implemented an additional button using the method outlined in this issue to automate the SSO login, rather then just lining back to the Server homepage. Specifically, I am hitting the auth proxy redirect URL for Jellyfin. So, if I set "Name of OID Provider" in the Jellyfin's SSO settings to "authentik" the redirect would be `/sso/OID/r/authentik`. Anyway, this works great! However, it does launch this URL in a separate tab, which is not ideal.

**So, is there any way to configure the button to open in the same tab?** I've tried adding `target="_self"` to the link.

**Comment by NeroPcStation** [comment]
> **So, is there any way to configure the button to open in the same tab?** I've tried adding `target="_self"` to the link.

It is hardcoded in Jellyfin web interface.

**Comment by FirbyKirby** [comment]
Awww. Bummer. But thanks for the quick answer! Still way better then nothing.

**Comment by adamzvolanek** [comment]
> "authentik" the redirect would be `/sso/OID/r/authentik`

Did you add the redirect like this to Authentik? 

![image](https://github.com/9p4/jellyfin-plugin-sso/assets/80661527/bdd8f218-84c4-4651-8553-fed0677a586b)


I am still trying to verify if the Authentik/JellyFin integration is working. So any help would be greatly appreciated!

**Comment by 9p4** [comment]
yes that looks correct

**Comment by 9p4** [comment]
Fixed in 076cb1b893711b664386d46f6ee8d776243a9061

**Comment by hendrik1120** [comment]
Hi, is it possible for the SSO Login button to follow the link in the same tab?
href should do that by default, but at least in safari and chrome it always opens in a new tab.
Is it possible to overwrite that somehow?

**Comment by 9p4** [comment]
It's hardcoded into the Jellyfin web interface code.

https://github.com/9p4/jellyfin-plugin-sso/issues/16#issuecomment-1591017300

**Comment by isavegas** [comment]
> Hi, is it possible for the SSO Login button to follow the link in the same tab? href should do that by default, but at least in safari and chrome it always opens in a new tab. Is it possible to overwrite that somehow?

You can use a form + button to cause the URL to be opened in the current tab. Works well on browsers, although the official Jellyfin app for Android hangs on "Logging in..."

```html
<form action="https://jellyfin.example.com/sso/OID/start/PROVIDER"><button class="raised button-sso block emby-button" type="submit">Sign In with SSO</button></form>
```

```css
button.raised.button-sso {
  background: #00a4dc;
}
```

**Comment by nibblerrick** [comment]
> You can use a form + button to cause the URL to be opened in the current tab. Works well on browsers, although the official Jellyfin app for Android hangs on "Logging in..." when using Authelia.

I just tested this with authentik. On IOS it logs in fine, on Android I have the same, hangs at "logging in..."

Thanks for the idea with the form, at least on IOS SSO login seems possible this way (direct SSO without Quickconnect, that option remains, of course).

**Comment by LeVraiRoiDHyrule** [comment]
> ```css
> button.raised.button-sso {
>   background: #00a4dc;
> }
> ```

You are my savior, thank you so much. This makes SSO work in Jellyfin Media Player, which my users have to use because most of my files are HEVC and can't be played on most browsers. Then quick connect will do the trick for the very few that use Kodi with the Jellyfin addon.

**Comment by Sapd** [comment]
If someone finds it useful. There is also a way to directly redirect to SSO if not logged in. Skipping the login-form completely.

I injected JS with nginx:

```js
    location /login-redirect.js {
        default_type application/javascript;
        add_header Content-Disposition "inline; filename=login-redirect.js";
        return 200 '
	    let timer
            function checkForSignIn() {
	        const isLoginPage = window.location.href.includes("login.html")
		if (isLoginPage) {
		    clearInterval(timer)
                    window.location.href = "/sso/OID/start/authentik"; // Change to your desired URL
                }
	        const isLoggedIn = window.location.href.includes("index.html")
		if (isLoggedIn) clearInterval(timer)
            }
            timer = setInterval(checkForSignIn, 10);
        ';
    }
```

Then inside location /web:
```
        sub_filter
        '</head>'
        '<script plugin="intro-skipper" src="configurationpage?name=skip-intro-button.js"></script>
        <script src="/login-redirect.js"></script>
	</head>';
```

It will simply periodically check if the user is at the Jellyfin login url. If yes it will redirect for authentication to SSO. If it detects that the user is at index.html (which is never called when not logged in) it will simply delete the timer.

**Comment by tecbeat** [comment]
Hi there,

First of all, thanks for the great work on the SSO plugin!

I’d like to suggest a small enhancement: it would be helpful to disable the manual login form entirely and only show the Quick Connect and SSO login buttons. This can be useful in setups where only external authentication should be used, providing a cleaner and more focused login interface.

Here’s a CSS snippet that achieves this effect, by hiding the standard login fields and simplifying the layout:

```css
a.raised.emby-button {
    color: inherit !important;
}

.btnForgotPassword {
    display: none !important;
}

.loginDisclaimerContainer,
.loginDisclaimer,
.manualLoginForm {
    all: unset;
}

.manualLoginForm {
    display: block !important;
}

.manualLoginForm > :not(:first-child) {
    display: none !important;
}

.manualLoginForm .sectionTitle {
    display: block !important;
    font-size: 2em;
    text-align: center;
    margin-top: 3em;
    color: inherit;
}
```
(working in sso-plugin v3.5.2.4 and jellyfin v10.10.7)

This disables the default login form and keeps only the Quick Connect / SSO buttons visible. 

Thanks again! 😊

![Image](https://github.com/user-attachments/assets/b2ad4f09-0d30-452d-bc36-ae33f5ff780e)

**Comment by e64462** [comment]
To me the Blue, Grey, Blue theme is super disorienting, so I changed the colors of the login disclaimer a bit

![Image](https://github.com/user-attachments/assets/9c4d82b5-0760-4009-a2a5-8210dc40de18)

```
<form action="https://jelly.sakur.us/sso/OID/start/authelia">
  <button class="raised block emby-button button-submit" style="background-color: firebrick; color: white;">
    <span>Authenticate with SSO</span>
  </button>
</form>
```

**Comment by Callumpy** [comment]
Good thread - I love the idea of the nginx redirect, however I want to keep the Quick Connect button available as well.

So I decided to go all out on my login page using a mix mash of the suggestions above to remove all unneeded options:

![Image](https://github.com/user-attachments/assets/d4491897-2ca7-4eb7-89a4-51ea48492e1c)

```css
a.raised.emby-button,
.loginDisclaimerContainer,
.loginDisclaimer,
.manualLoginForm {
  all: unset;
}

.btnQuick,
.btnSelectServer,
.btnForgotPassword,
a.raised.emby-button,
.emby-button.block,
.loginDisclaimerContainer,
.loginDisclaimer {
  margin-left: auto;
  margin-right: auto;
  margin-bottom: 1em;
  color: inherit !important;
}

.btnForgotPassword {
  display: none !important;
}

.manualLoginForm > :not(:first-child) {
  display: none !important;
}

.sso-icon {
  width: 25px;
  height: 25px;
  vertical-align: middle;
  margin-right: 5px;
}
```

```html
<form action="https://jellyfin.example.com/sso/OID/start/authelia">
  <button class="raised block emby-button button-submit">
    <img src="https://www.authelia.com/svgs/branding/logo-cropped.svg" alt="Authelia Logo" class="sso-icon">
    Sign in with Authelia
  </button>
</form>
```
