### ISSUE TITLE
Add option to Skip SSL/TLS Verification

### ISSUE THREAD

**Issue by nununo** [9p4/jellyfin-plugin-sso#215]
**Is your feature request related to a problem? Please describe.**

My Authentik server uses a certificate issued by my own self-signed CA. And my Jellyfin Docker container doesn't trust it. So in the plugin logs I see an exception: "The SSL connection could not be established, see inner exception".

**Describe the solution you'd like**

I would like to have an option to _Skip SSL/TLS Verification_ similar to what exists today in the LDAP plugin. So that all requests would be made without verifying the TLS certificate.

**Comment by 9p4** [comment]
I'd prefer that you built a custom Jellyfin image with your SSL root certificate installed. I want to avoid adding complexity (and a greater risk of misconfiguration) to this plugin.

**Comment by nekrich** [comment]
In case someone else stumbles upon this.

For the Jellyfin SSO Plugin to trust the self-signed certificate, the solution is to change the Docker Compose file by adding:
1. A volume with the Root CA certificate (from step-ca in my case), 
2. ENV var `SSL_CERT_DIR` with a path to the certificates location.

After I made those changes, everything worked like a charm, and the plug-in was finally able to trust the self-signed certs.

```yaml
volumes:
  ${APP_DATA_DIR}/step-ca/certs/root_ca.crt:/usr/local/share/ca-certificates/step-ca-root_ca.crt:ro

environment:
  SSL_CERT_DIR: /usr/local/share/ca-certificates

```

More info on the `SSL_CERT_DIR` environment variable: [ASP .NET docs on OpenSSL trust](https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-9.0&tabs=visual-studio%2Clinux-sles#openssl-trust).
