### ISSUE TITLE
Allow configuration of OIDC scopes to request to support role-claim

### ISSUE THREAD

**Issue by matthewstrasiotto** [9p4/jellyfin-plugin-sso#23]
**Is your feature request related to a problem? Please describe.**

I recently decided to try to configure role-based access. I used the following configuration:

```yaml
---
authelia:
  OidEndpoint: https://authelia.example.com/.well-known/openid-configuration/
  OidClientId: jellyfin
  OidSecret: <omitted>
  Enabled: true
  EnableAuthorization: true
  EnableAllFolders: true
  EnabledFolders: []
  Roles: ["jellyfin_user"]
  AdminRoles: ["jellyfin_admin"]
  EnableFolderRoles: false
  FolderRoleMapping: []
  RoleClaim: groups
```

Fields of interest are here:
```yaml
authelia:
  Roles: ["jellyfin_user"]
  AdminRoles: ["jellyfin_admin"]
  RoleClaim: groups
```

However, I found the response was "Error. Check Permissions", with the following log entry:

```
[12:57:50] [WRN] [7] Jellyfin.Plugin.SSO_Auth.Api.SSOController: OpenID user su has one or more incorrect role claims: [{"Type": "jti", "Value": "***redacted***"}, {"Type": "name", "Value": "Superuser"}, {"Type": "preferred_username", "Value": "su"}, {"Type": "rat", "Value": "1651114669"}, {"Type": "sub", "Value": "su"}]. Expected any one of: ["jellyfin_user"]
```

Per the authelia oidc config spec: https://www.authelia.com/docs/configuration/identity-providers/oidc.html#groups , I learned that the "groups" attribute requires the client to request the "groups" scope. 

To test this, I modified the request to include this scope:

https://github.com/9p4/jellyfin-plugin-sso/compare/main...matthewstrasiotto:authelia_groups?expand=1 

```diff
diff --git a/SSO-Auth/Api/SSOController.cs b/SSO-Auth/Api/SSOController.cs
index ad60764..f24e44e 100644
--- a/SSO-Auth/Api/SSOController.cs
+++ b/SSO-Auth/Api/SSOController.cs
@@ -76,7 +76,7 @@ public SSOController(ILogger<SSOController> logger, ISessionManager sessionManag
                 ClientId = config.OidClientId,
                 ClientSecret = config.OidSecret,
                 RedirectUri = GetRequestBase() + "/sso/OID/r/" + provider,
-                Scope = "openid profile",
+                Scope = "openid profile groups",
             };
             options.Policy.Discovery.ValidateEndpoints = false; // For Google and other providers with different endpoints
             var oidcClient = new OidcClient(options);
@@ -243,7 +243,7 @@ public async Task<ActionResult> OidChallenge(string provider)
                 ClientId = config.OidClientId,
                 ClientSecret = config.OidSecret,
                 RedirectUri = GetRequestBase() + "/sso/OID/r/" + provider,
-                Scope = "openid profile"
+                Scope = "openid profile groups"
             };
             options.Policy.Discovery.ValidateEndpoints = false; // For Google and other providers with different endpoints
             var oidcClient = new OidcClient(options);
```

And indeed, requesting "groups" correctly confers user roles as well as admin roles.
It appears that for some OIDC providers,  (Authelia, at the very least), additional scopes may need to be requested.

**Describe the solution you'd like**

Rather than hard-code these scopes into the request as I did to test the matter, I propose adding an additional config option, "additional oidc scopes" (or something) that allows the user to specify additional scopes to include in the request.

**Describe alternatives you've considered**

Hard-code this in, allow more opinionated provider presets (Preset, keycloak, preset authelia, etc), for my own use-case I could probably have supplied a list of usernames i wanted to get admin, but this defeats the purpose of membership based role checking. (All of these ideas are bad)
