### ISSUE TITLE
[HELP] After logging in using Authelia, I get stuck at Logging in...

### ISSUE THREAD

**Issue by erikthegamer1242** [9p4/jellyfin-plugin-sso#60]
Sorry if I asked in the wrong place.
So I added the sso plugin, configured it, and added an oidc config in Authelia. After going to https://jelly.mydomain.com/sso/OID/p/Authelia it forwards me to the consent page, and I click allow. Then it redirects back to jellyfin but gets stuck on a white page showing Logging in... The problem might be that I am using Cloudflare as a DNS/proxy, and they don't allow anything except HTML, so I turned off proxying for jellyfin. And somehow my cert seems to be only for my root domain and it is not a wildcard cert.

This is my config:
```XML
SSO-Auth.xml
<?xml version="1.0" encoding="utf-8"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <SamlConfigs />
  <OidConfigs>
    <item>
      <key>
        <string>Authelia</string>
      </key>
      <value>
        <PluginConfiguration>
          <OidEndpoint>https://auth.mydomain.com/.well-known/openid-configuration</OidEndpoint>
          <OidClientId>jellyfin</OidClientId>
          <OidSecret>REDACTED</OidSecret>
          <Enabled>true</Enabled>
          <EnableAuthorization>true</EnableAuthorization>
          <EnableAllFolders>true</EnableAllFolders>
          <EnabledFolders />
          <AdminRoles>
            <string>admins</string>
          </AdminRoles>
          <Roles>
            <string>user</string>
            <string>admins</string>
          </Roles>
          <EnableFolderRoles>false</EnableFolderRoles>
          <FolderRoleMappings />
          <RoleClaim>groups</RoleClaim>
          <OidScopes>
            <string>groups</string>
          </OidScopes>
          <DefaultProvider>Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider </DefaultProvider>
        </PluginConfiguration>
      </value>
    </item>
  </OidConfigs>
</PluginConfiguration>
```

```YAML
configuration.yml
      - id: jellyfin
        description: JellyFin
        secret: REDACTED
        public: false
        authorization_policy: two_factor
        audience: []
        scopes:
          - openid
          - groups
          - email
          - profile
        redirect_uris:
          - https://jelly.mydomain.com/sso/OID/r/Authelia
        grant_types:
          - refresh_token
          - authorization_code
        response_types:
          - code
        response_modes:
          - form_post
          - query
          - fragment
        userinfo_signing_algorithm: none
```

![image](https://user-images.githubusercontent.com/71411196/183085155-3abbb32e-48a3-4fd1-837b-6077de11bb32.png)
This is the screen after clicking allow in Authelia
